import speech_recognition as sr
import openai

openai.api_key = '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'

recognizer = sr.Recognizer()

with sr.Microphone() as source: #creates a Microphone object and opens a connection to the system's default microphone
    print("Say something:") #prints a message to the console, prompting the user to say something.
    audio = recognizer.listen(source) # records audio from the microphone using the listen method of the Recognizer object. The recorded audio is stored in the audio variable

try:
    text_input = recognizer.recognize_google(audio)
    print("You said:", text_input)
except sr.UnknownValueError:
    print("Sorry, could not understand audio.")
except sr.RequestError as e:
    print(f"Error with the speech recognition service: {e}")
    
response = openai.Completion.create( #method provided by the OpenAI Python library to interact with the GPT-3 API for generating completions.
    engine="text-davinci-003", #Specifies the GPT-3 engine to be used
    prompt=text_input, #The text_input variable holds the prompt or input text that you want GPT-3 to complete or generate a response for.
    max_tokens=150 # Specifies the maximum number of tokens (words or characters) that the generated response should have
)

chatgpt_output = response.choices[0].text.strip() #chatgpt_output contains the cleaned and processed output text generated by GPT-3 in response to the provided prompt.

